version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    environment:
      - TZ=UTC
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 3306:3306
    volumes:
      - "./api/tmp/db:/var/lib/postgresql/data"

  api:
    build:
      context: ./api
      args:
        WORKDIR: app
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - "./api:/app"
    ports:
      - "$API_PORT:3000"
    depends_on:
      - db
  
  front:
    build:
      context: ./frontend
      args:
        WORKDIR: app
    command: npm start
    volumes:
      - "./frontend:/app"
    ports:
      - "$FRONT_PORT:3000"
    depends_on:
      - api
