version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0

executors:
  default:
    docker:
      - image: cimg/node:18.12.1
      - image: cimg/python:3.6
        environment:
          NODE_ENV: production

commands:
  npm_install:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

jobs:  
  build_and_deploy:
    executor: default
    working_directory: ~/repo/front
    steps:
      - checkout
      - npm_install
      - run:
          name: build
          command: npm run build
      - aws-s3/sync:
          from: build
          to: s3://tasting-note-staging

workflows:
  test_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              ignore: main
